#include <oraccsys.h>
#include <form.h>

#define psu_cat(xff,xfld)			\
  int i, len = 0;				\
  for (i = 0; xff[i]; ++i)			\
    if (xff[i]->xfld)				\
      len += strlen((ccp)xff[i]->xfld);		\
    else					\
      return NULL;				\
  len += i;					\
  char buf[len+1];				\
  *buf = '\0';					\
  for (i = 0; xff[i]; ++i)			\
    {						\
      if (i)					\
	strcat(buf, "_");			\
      strcat(buf, (ccp)xff[i]->xfld);		\
    }						\
  return pool_copy((uccp)buf, p);

static unsigned char *psu_form(Form **ff, Pool *p)   { psu_cat(ff,form); }
static unsigned char *psu_norm(Form **ff, Pool *p)   { psu_cat(ff,norm); }
static unsigned char *psu_stem(Form **ff, Pool *p)   { psu_cat(ff,stem); }
static unsigned char *psu_base(Form **ff, Pool *p)   { psu_cat(ff,base); }
static unsigned char *psu_cont(Form **ff, Pool *p)   { psu_cat(ff,cont); }
static unsigned char *psu_morph(Form **ff, Pool *p)  { psu_cat(ff,morph); }
static unsigned char *psu_morph2(Form **ff, Pool *p) { psu_cat(ff,morph2); }

void
phrase_fields(Form *pf, Form **ff, Pool *p)
{
  pf->form = psu_form(ff, p);
  pf->norm = psu_norm(ff, p);
  pf->stem = psu_stem(ff, p);
  pf->base = psu_base(ff, p);
#if 0
  /* if phrase tokens are needed they have to be generated by caller
     after calling phrase_fields */
  if (pf->base)
    pf->b = gt_token(mp, (ucp)pf->base, 0, NULL);
#endif
  pf->cont   = psu_cont(ff, p);
  pf->morph  = psu_morph(ff, p);
  pf->morph2 = psu_morph2(ff, p);
}
