
#line 2 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer atf_create_buffer
#define yy_delete_buffer atf_delete_buffer
#define yy_scan_buffer atf_scan_buffer
#define yy_scan_string atf_scan_string
#define yy_scan_bytes atf_scan_bytes
#define yy_init_buffer atf_init_buffer
#define yy_flush_buffer atf_flush_buffer
#define yy_load_buffer_state atf_load_buffer_state
#define yy_switch_to_buffer atf_switch_to_buffer
#define yypush_buffer_state atfpush_buffer_state
#define yypop_buffer_state atfpop_buffer_state
#define yyensure_buffer_stack atfensure_buffer_stack
#define yy_flex_debug atf_flex_debug
#define yyin atfin
#define yyleng atfleng
#define yylex atflex
#define yylineno atflineno
#define yyout atfout
#define yyrestart atfrestart
#define yytext atftext
#define yywrap atfwrap
#define yyalloc atfalloc
#define yyrealloc atfrealloc
#define yyfree atffree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define atf_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer atf_create_buffer
#endif

#ifdef yy_delete_buffer
#define atf_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer atf_delete_buffer
#endif

#ifdef yy_scan_buffer
#define atf_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer atf_scan_buffer
#endif

#ifdef yy_scan_string
#define atf_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string atf_scan_string
#endif

#ifdef yy_scan_bytes
#define atf_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes atf_scan_bytes
#endif

#ifdef yy_init_buffer
#define atf_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer atf_init_buffer
#endif

#ifdef yy_flush_buffer
#define atf_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer atf_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define atf_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state atf_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define atf_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer atf_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define atfpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state atfpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define atfpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state atfpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define atfensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack atfensure_buffer_stack
#endif

#ifdef yylex
#define atflex_ALREADY_DEFINED
#else
#define yylex atflex
#endif

#ifdef yyrestart
#define atfrestart_ALREADY_DEFINED
#else
#define yyrestart atfrestart
#endif

#ifdef yylex_init
#define atflex_init_ALREADY_DEFINED
#else
#define yylex_init atflex_init
#endif

#ifdef yylex_init_extra
#define atflex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra atflex_init_extra
#endif

#ifdef yylex_destroy
#define atflex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy atflex_destroy
#endif

#ifdef yyget_debug
#define atfget_debug_ALREADY_DEFINED
#else
#define yyget_debug atfget_debug
#endif

#ifdef yyset_debug
#define atfset_debug_ALREADY_DEFINED
#else
#define yyset_debug atfset_debug
#endif

#ifdef yyget_extra
#define atfget_extra_ALREADY_DEFINED
#else
#define yyget_extra atfget_extra
#endif

#ifdef yyset_extra
#define atfset_extra_ALREADY_DEFINED
#else
#define yyset_extra atfset_extra
#endif

#ifdef yyget_in
#define atfget_in_ALREADY_DEFINED
#else
#define yyget_in atfget_in
#endif

#ifdef yyset_in
#define atfset_in_ALREADY_DEFINED
#else
#define yyset_in atfset_in
#endif

#ifdef yyget_out
#define atfget_out_ALREADY_DEFINED
#else
#define yyget_out atfget_out
#endif

#ifdef yyset_out
#define atfset_out_ALREADY_DEFINED
#else
#define yyset_out atfset_out
#endif

#ifdef yyget_leng
#define atfget_leng_ALREADY_DEFINED
#else
#define yyget_leng atfget_leng
#endif

#ifdef yyget_text
#define atfget_text_ALREADY_DEFINED
#else
#define yyget_text atfget_text
#endif

#ifdef yyget_lineno
#define atfget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno atfget_lineno
#endif

#ifdef yyset_lineno
#define atfset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno atfset_lineno
#endif

#ifdef yywrap
#define atfwrap_ALREADY_DEFINED
#else
#define yywrap atfwrap
#endif

#ifdef yyalloc
#define atfalloc_ALREADY_DEFINED
#else
#define yyalloc atfalloc
#endif

#ifdef yyrealloc
#define atfrealloc_ALREADY_DEFINED
#else
#define yyrealloc atfrealloc
#endif

#ifdef yyfree
#define atffree_ALREADY_DEFINED
#else
#define yyfree atffree
#endif

#ifdef yytext
#define atftext_ALREADY_DEFINED
#else
#define yytext atftext
#endif

#ifdef yyleng
#define atfleng_ALREADY_DEFINED
#else
#define yyleng atfleng
#endif

#ifdef yyin
#define atfin_ALREADY_DEFINED
#else
#define yyin atfin
#endif

#ifdef yyout
#define atfout_ALREADY_DEFINED
#else
#define yyout atfout
#endif

#ifdef yy_flex_debug
#define atf_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug atf_flex_debug
#endif

#ifdef yylineno
#define atflineno_ALREADY_DEFINED
#else
#define yylineno atflineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define atfwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[349] =
    {   0,
        0,    0,    0,    0,   20,   18,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,    0,   16,    0,    0,   15,    0,    0,    0,
        0,    0,    0,   12,    0,    0,    0,    0,    6,    0,
        0,    0,    0,    3,    0,    0,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    0,    0,    0,   14,    0,
        0,    0,    0,   12,    0,    0,    0,    0,    6,    0,
        0,    0,    0,    3,    0,    0,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    0,    0,    9,    0,   13,

        0,    0,    9,    0,    0,    0,    0,    6,    0,    0,
        3,    0,    0,    0,    8,    0,    0,    0,    0,   11,
        0,    0,    0,    5,    0,    0,    0,    0,    0,    9,
        0,    0,    0,    9,    0,    0,    0,    0,    6,    0,
        0,    3,    0,    0,    0,    8,    0,    0,    0,    0,
       11,    0,    0,    0,    5,    0,    0,    0,    0,    0,
        0,    0,    0,   10,    0,    0,    0,    0,    0,   10,
        0,    0,    0,    0,    6,    0,    0,    0,    0,    3,
        0,    8,    0,    0,    9,    0,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    2,    0,    0,    0,    0,

        0,    0,   10,    0,    0,    0,    0,    0,   10,    0,
        0,    0,    0,    6,    0,    0,    0,    0,    3,    0,
        8,    0,    0,    9,    0,    0,    0,    0,    0,    5,
        0,    0,    0,    0,    2,    0,    0,    0,    0,    7,
        0,    0,    0,    0,    8,    0,    0,    0,    0,   10,
        0,    0,    0,    1,    0,    0,    0,    2,    0,    0,
        0,    7,    0,    0,    0,    0,    8,    0,    0,    0,
        0,   10,    0,    0,    0,    1,    0,    0,    0,    2,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    2,
        0,    0,    1,    0,    0,    0,    0,    0,    2,    0,

        0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
        1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    0,    0,    0,    0,    4,    0,
        0,    0,    4,    0,    0,    4,    0,    0,    0,    0,
        0,    4,    0,    0,    0,    0,    4,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    6,    1,    1,
        1,    1,    7,    1,    1,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,    1,   10,
       11,   12,    1,   13,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   14,    1,    1,    1,

        1,    1,    1,    1,   15,    1,    1,   16,    1,   17,
       18,    1,    1,   19,   20,   21,    1,    1,    1,    1,
        1,    1,    1,   22,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   23,    1,    1,    1,
       24,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   25,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   26,   27
    } ;

static const YY_CHAR yy_meta[28] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[435] =
    {   0,
      833,    0,  832,   27,  834, 1025,   53,   55,  831,   57,
       59,   67,   75,   83,   92,  102,  113,  133,  154,  176,
       71,  104,  115,  117,  202,  210,  219,  229,  240,  260,
      281,  303,   69, 1025,  129,  829, 1025,  137,  141,  828,
       85,  145,  825, 1025,  156,  158,  166,  824, 1025,  178,
      180,  188,  823, 1025,  190,  192,  231,  242,  244,  822,
     1025,  256,  264,  329,  347,  370,  268,  818, 1025,  272,
      283,  285,  817, 1025,  293,  305,  307,  816, 1025,  315,
      317,  319,  815, 1025,  331,  333,  343,  351,  355,  814,
     1025,  359,  372,  380,  398,  421,   87, 1025,   94, 1025,

      382,   96, 1025,  384,  106,  394,  125, 1025,  127,  149,
     1025,  168,  402,  813, 1025,  406,  410,  423,  812, 1025,
      431,  433,  170, 1025,  204,  441,  454,  443,  212, 1025,
      214,  445,  221, 1025,  456,  223,  464,  233, 1025,  252,
      254, 1025,  276,  466,  811, 1025,  468,  476,  478,  808,
     1025,  480,  488,  295, 1025,  297,  496,  509,  492,  807,
      341,  806,  363, 1025,  367,  805,  392,  801,  414, 1025,
      800,  418,  799,  435, 1025,  798,  490,  797,  500, 1025,
      504, 1025,  506,  511, 1025,  517,  796,  519,  795,  521,
     1025,  523,  525,  527,  794, 1025,  535,  539,  791,  543,

      790,  547, 1025,  549,  789,  551,  788,  553, 1025,  784,
      555,  783,  557, 1025,  782,  559,  781,  561, 1025,  563,
     1025,  565,  567, 1025,  569,  780,  571,  777,  573, 1025,
      575,  577,  579,  776, 1025,  587,  591,  770,  595, 1025,
      756,  599,  736,  601, 1025,  703,  603,  700,  605, 1025,
      607,  609,  656, 1025,  611,  620,  622, 1025,  628,  651,
      630, 1025,  623,  632,  618,  634, 1025,  588,  636,  536,
      638, 1025,  640,  642,  513, 1025,  644,  653,  655, 1025,
      661,  663,  665, 1025,  667,  458,  671,  425,  673, 1025,
      678,  675, 1025,  680,  395,  682,  374,  686, 1025,  693,

      344,  688,  326,  690, 1025,  706,  300,  695,  257,  697,
     1025,  719,  739,  759,  773,  787,  804,  821,  837,  702,
      710,  721,  226, 1025,  723,  735,  743,  205, 1025,  747,
      755,  714, 1025,  731,  733, 1025,  751,  199,  763,  173,
      767, 1025,  130,  769,   99,  775, 1025, 1025,  854,  856,
       80,  858,  860,  862,  864,  866,  868,  870,  872,  874,
      876,  878,  880,  882,  884,  886,  888,  890,  892,  894,
      896,  898,  900,  902,  904,  906,  908,  910,  912,  914,
      916,  918,  920,  922,  924,  926,  928,  930,  932,  934,
      936,  938,  940,  942,  944,  946,  948,  950,  952,  954,

      956,  958,  960,  962,  964,  966,  968,  970,  972,  974,
      976,  978,  980,  982,  984,  986,  988,  990,  992,  994,
      996,  998, 1000, 1002, 1004, 1006, 1008, 1010, 1012, 1014,
     1016, 1018, 1020, 1022
    } ;

static const flex_int16_t yy_def[435] =
    {   0,
      349,  348,  349,  348,  348,  348,  348,  350,  351,  352,
      353,  354,  350,  350,  350,  350,  355,  350,  350,  350,
      356,  357,  358,  359,  356,  356,  356,  356,  360,  356,
      356,  356,  348,  348,  350,  361,  348,  350,  350,  351,
      351,  352,  362,  348,  352,  363,  353,  364,  348,  353,
      353,  354,  365,  348,  354,  354,  366,  367,  355,  368,
      348,  355,  355,  355,  350,  350,  356,  369,  348,  356,
      356,  357,  370,  348,  357,  371,  358,  372,  348,  358,
      358,  359,  373,  348,  359,  359,  374,  375,  360,  376,
      348,  360,  360,  360,  356,  356,  377,  348,  378,  348,

      363,  379,  348,  363,  380,  363,  381,  348,  382,  383,
      348,  384,  366,  385,  348,  366,  366,  367,  386,  348,
      367,  367,  387,  348,  388,  355,  350,  389,  390,  348,
      391,  371,  392,  348,  371,  393,  371,  394,  348,  395,
      396,  348,  397,  374,  398,  348,  374,  374,  375,  399,
      348,  375,  375,  400,  348,  401,  360,  356,  402,  377,
      377,  378,  378,  348,  403,  379,  379,  380,  380,  348,
      381,  381,  382,  382,  348,  383,  383,  384,  384,  348,
      404,  348,  405,  406,  348,  407,  387,  387,  388,  388,
      348,  355,  408,  389,  409,  348,  389,  389,  390,  390,

      391,  391,  348,  410,  392,  392,  393,  393,  348,  394,
      394,  395,  395,  348,  396,  396,  397,  397,  348,  411,
      348,  412,  413,  348,  414,  400,  400,  401,  401,  348,
      360,  415,  402,  416,  348,  402,  402,  403,  403,  348,
      404,  404,  405,  405,  348,  406,  406,  407,  407,  348,
      355,  408,  417,  348,  408,  408,  418,  348,  419,  410,
      410,  348,  411,  411,  412,  412,  348,  413,  413,  414,
      414,  348,  360,  415,  420,  348,  415,  415,  421,  348,
      422,  355,  423,  348,  424,  418,  418,  419,  419,  348,
      360,  425,  348,  426,  421,  421,  422,  422,  348,  355,

      423,  423,  424,  424,  348,  360,  425,  425,  426,  426,
      348,  355,  360,  355,  360,  355,  360,  355,  360,  427,
      428,  427,  429,  348,  427,  427,  428,  430,  348,  428,
      428,  431,  348,  432,  433,  348,  434,  431,  431,  432,
      432,  348,  433,  433,  434,  434,  348,    0,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348
    } ;

static const flex_int16_t yy_nxt[1053] =
    {   0,
        8,    9,    7,   10,   11,   12,   13,    8,    8,   14,
       15,   16,   17,    8,    8,    8,    8,    8,    8,    8,
        8,   18,    8,    8,   19,   20,    8,   21,    9,    7,
       22,   23,   24,   25,   21,   21,   26,   27,   28,   29,
       21,   21,   21,   21,   21,   21,   21,   21,   30,   21,
       21,   31,   32,   21,   33,   34,   36,   37,   43,   44,
       48,   49,   38,   39,   45,   46,   50,   51,   53,   54,
       33,   34,   68,   69,   55,   56,   36,   37,   70,   71,
       40,   57,   38,   39,   36,   37,   41,  100,  161,   98,
       38,   39,   57,   36,   37,  163,  164,  167,  103,   38,

       39,  347,   58,   36,   37,   73,   74,  169,  170,   38,
       39,   75,   76,   57,   60,   61,   78,   79,   83,   84,
       62,   63,   80,   81,   85,   86,  172,  108,  174,  175,
       36,   37,  336,   64,   36,   37,   38,   39,   97,   98,
       38,   39,   99,   37,   38,   39,   43,   44,   38,   39,
      177,  111,   45,  101,   57,   36,   37,  102,  103,  105,
       44,   38,   39,   45,  101,  106,   46,   48,   49,  179,
      180,  188,  124,   50,   51,  342,   65,   36,   37,  107,
      108,  109,   49,   38,   39,   50,   51,   50,   51,   53,
       54,  110,  111,  112,   54,   55,   56,   55,   56,   55,

       56,  333,   66,   68,   69,  190,  191,  329,   87,   70,
       71,   68,   69,  200,  130,  202,  203,   70,   71,   87,
       68,   69,  206,  134,  208,  209,   70,   71,  324,   88,
       68,   69,  114,  115,  211,  139,   70,   71,  116,  117,
       87,   90,   91,  119,  120,   60,   61,   92,   93,  121,
      122,   62,   63,  213,  214,  216,  142,  123,  124,  311,
       94,   68,   69,   62,   63,  125,   61,   70,   71,   68,
       69,   62,   63,  129,  130,   70,   71,  218,  219,   70,
       71,   87,   68,   69,  131,   69,   73,   74,   70,   71,
       70,   71,   75,  132,  133,  134,  227,  155,  229,  230,

       75,  132,  293,   95,   68,   69,  136,   74,   78,   79,
       70,   71,  137,   76,   80,   81,  138,  139,  140,   79,
       83,   84,   80,   81,   80,   81,   85,   86,  305,   96,
       60,   61,  141,  142,  143,   84,   62,   63,   85,   86,
       85,   86,  161,   98,  145,  146,  284,  126,   36,   37,
      147,  148,  150,  151,   38,   39,   90,   91,  152,  153,
      154,  155,   92,   93,  163,  164,   92,   93,  239,  240,
      127,   36,   37,  156,   91,  128,  299,   38,   39,   92,
       93,   90,   91,  165,   44,   43,   44,   92,   93,  106,
       46,  106,   46,  167,  103,  102,  103,  280,  157,   68,

       69,  106,   46,  114,  115,   70,   71,  181,  182,  116,
      117,  183,  115,  116,  117,  169,  170,  116,  117,  172,
      108,  158,   68,   69,  119,  120,  159,  290,   70,   71,
      121,  122,  184,  185,  186,  120,  174,  175,  121,  122,
      121,  122,   60,   61,  195,  196,  204,   74,   62,   63,
      197,  198,  137,   76,  192,   36,   37,   73,   74,  193,
      258,   38,   39,  137,   76,  133,  134,  145,  146,  220,
      221,  137,   76,  147,  148,  147,  148,  222,  146,  150,
      151,  223,  224,  147,  148,  152,  153,  152,  153,  225,
      151,  177,  111,  234,  235,  152,  153,   90,   91,  236,

      237,  179,  180,   92,   93,  242,  182,  244,  245,  231,
       68,   69,  247,  185,  232,  276,   70,   71,  249,  250,
      188,  124,  190,  191,   60,   61,  253,  254,  195,  196,
       62,   63,  255,  256,  197,  198,  257,  258,  272,  251,
      259,  196,  197,  198,  200,  130,  197,  198,  202,  203,
      261,  262,  206,  134,  208,  209,  211,  139,  213,  214,
      216,  142,  218,  219,  264,  221,  266,  267,  269,  224,
      271,  272,  227,  155,  229,  230,   90,   91,  275,  276,
      234,  235,   92,   93,  277,  278,  236,  237,  279,  280,
      224,  273,  281,  235,  236,  237,  239,  240,  236,  237,

      242,  182,  244,  245,  247,  185,  249,  250,   60,   61,
      253,  254,  283,  284,   62,   63,  255,  256,  255,  256,
      267,  285,  254,  287,  258,  221,  282,  255,  256,  289,
      290,  261,  262,  264,  221,  266,  267,  269,  224,  271,
      272,   90,   91,  275,  276,  292,  293,   92,   93,  277,
      278,  277,  278,  262,  294,  276,  296,  280,  254,  291,
      277,  278,  298,  299,   60,   61,  302,  284,  304,  305,
       62,   63,  287,  258,  289,  290,  308,  293,  300,   90,
       91,  310,  311,  296,  280,   92,   93,  298,  299,  302,
      284,  304,  305,  306,   60,   61,  308,  293,  310,  311,

       62,   63,  250,  323,  324,  185,  312,   90,   91,  325,
      326,  328,  329,   92,   93,  339,  333,  330,  331,  313,
       60,   61,  323,  324,  332,  333,   62,   63,  325,  326,
      325,  326,  341,  342,  344,  336,  334,  324,  245,  314,
       90,   91,  325,  326,  328,  329,   92,   93,  335,  336,
      330,  331,  346,  347,  330,  331,  337,  329,  182,  315,
       60,   61,  330,  331,  339,  333,   62,   63,  341,  342,
      344,  336,  240,  316,   90,   91,  346,  347,  235,  230,
       92,   93,  155,  219,  142,  214,  139,  317,   60,   61,
      209,  134,  203,  130,   62,   63,  196,  191,  124,  180,

      111,  175,  108,  170,  318,   90,   91,  103,  164,   98,
      151,   92,   93,  146,  120,  115,   91,   84,   79,   74,
       69,  319,   60,   61,   61,   54,   49,   44,   62,   63,
      100,   37,   41,  348,    7,    7,  348,  320,   90,   91,
      348,  348,  348,  348,   92,   93,  348,  348,  348,  348,
      348,  348,  348,  321,    6,    6,   35,   35,   42,   42,
       47,   47,   52,   52,   59,   59,   67,   67,   72,   72,
       77,   77,   82,   82,   89,   89,   36,   36,   43,   43,
      104,  104,   48,   48,   53,   53,  113,  113,  118,  118,
       60,   60,   68,   68,   73,   73,  135,  135,   78,   78,

       83,   83,  144,  144,  149,  149,   90,   90,  160,  160,
      162,  162,  166,  166,  168,  168,  171,  171,  173,  173,
      176,  176,  178,  178,  114,  114,  119,  119,  187,  187,
      189,  189,  194,  194,  199,  199,  201,  201,  205,  205,
      207,  207,  210,  210,  212,  212,  215,  215,  217,  217,
      145,  145,  150,  150,  226,  226,  228,  228,  233,  233,
      238,  238,  241,  241,  243,  243,  246,  246,  248,  248,
      252,  252,  195,  195,  260,  260,  263,  263,  265,  265,
      268,  268,  270,  270,  274,  274,  234,  234,  253,  253,
      286,  286,  288,  288,  275,  275,  295,  295,  297,  297,

      301,  301,  303,  303,  307,  307,  309,  309,  322,  322,
      327,  327,  323,  323,  328,  328,  338,  338,  340,  340,
      343,  343,  345,  345,    5,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348
    } ;

static const flex_int16_t yy_chk[1053] =
    {   0,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    7,    7,    8,    8,   10,   10,
       11,   11,    8,    8,   10,   10,   11,   11,   12,   12,
       33,   33,   21,   21,   12,   12,   13,   13,   21,   21,
      351,   13,   13,   13,   14,   14,   41,   41,   97,   97,
       14,   14,   14,   15,   15,   99,   99,  102,  102,   15,

       15,  345,   15,   16,   16,   22,   22,  105,  105,   16,
       16,   22,   22,   16,   17,   17,   23,   23,   24,   24,
       17,   17,   23,   23,   24,   24,  107,  107,  109,  109,
       35,   35,  343,   17,   18,   18,   35,   35,   38,   38,
       18,   18,   39,   39,   38,   38,   42,   42,   39,   39,
      110,  110,   42,   42,   18,   19,   19,   45,   45,   46,
       46,   19,   19,   45,   45,   46,   46,   47,   47,  112,
      112,  123,  123,   47,   47,  340,   19,   20,   20,   50,
       50,   51,   51,   20,   20,   50,   50,   51,   51,   52,
       52,   55,   55,   56,   56,   52,   52,   55,   55,   56,

       56,  338,   20,   25,   25,  125,  125,  328,   25,   25,
       25,   26,   26,  129,  129,  131,  131,   26,   26,   26,
       27,   27,  133,  133,  136,  136,   27,   27,  323,   27,
       28,   28,   57,   57,  138,  138,   28,   28,   57,   57,
       28,   29,   29,   58,   58,   59,   59,   29,   29,   58,
       58,   59,   59,  140,  140,  141,  141,   62,   62,  309,
       29,   30,   30,   62,   62,   63,   63,   30,   30,   67,
       67,   63,   63,   70,   70,   67,   67,  143,  143,   70,
       70,   30,   31,   31,   71,   71,   72,   72,   31,   31,
       71,   71,   72,   72,   75,   75,  154,  154,  156,  156,

       75,   75,  307,   31,   32,   32,   76,   76,   77,   77,
       32,   32,   76,   76,   77,   77,   80,   80,   81,   81,
       82,   82,   80,   80,   81,   81,   82,   82,  303,   32,
       64,   64,   85,   85,   86,   86,   64,   64,   85,   85,
       86,   86,  161,  161,   87,   87,  301,   64,   65,   65,
       87,   87,   88,   88,   65,   65,   89,   89,   88,   88,
       92,   92,   89,   89,  163,  163,   92,   92,  165,  165,
       65,   66,   66,   93,   93,   66,  297,   66,   66,   93,
       93,   94,   94,  101,  101,  104,  104,   94,   94,  101,
      101,  104,  104,  167,  167,  106,  106,  295,   94,   95,

       95,  106,  106,  113,  113,   95,   95,  116,  116,  113,
      113,  117,  117,  116,  116,  169,  169,  117,  117,  172,
      172,   95,   96,   96,  118,  118,   96,  288,   96,   96,
      118,  118,  121,  121,  122,  122,  174,  174,  121,  121,
      122,  122,  126,  126,  128,  128,  132,  132,  126,  126,
      128,  128,  132,  132,  126,  127,  127,  135,  135,  127,
      286,  127,  127,  135,  135,  137,  137,  144,  144,  147,
      147,  137,  137,  144,  144,  147,  147,  148,  148,  149,
      149,  152,  152,  148,  148,  149,  149,  152,  152,  153,
      153,  177,  177,  159,  159,  153,  153,  157,  157,  159,

      159,  179,  179,  157,  157,  181,  181,  183,  183,  157,
      158,  158,  184,  184,  158,  275,  158,  158,  186,  186,
      188,  188,  190,  190,  192,  192,  193,  193,  194,  194,
      192,  192,  193,  193,  194,  194,  197,  197,  270,  192,
      198,  198,  197,  197,  200,  200,  198,  198,  202,  202,
      204,  204,  206,  206,  208,  208,  211,  211,  213,  213,
      216,  216,  218,  218,  220,  220,  222,  222,  223,  223,
      225,  225,  227,  227,  229,  229,  231,  231,  232,  232,
      233,  233,  231,  231,  232,  232,  233,  233,  236,  236,
      268,  231,  237,  237,  236,  236,  239,  239,  237,  237,

      242,  242,  244,  244,  247,  247,  249,  249,  251,  251,
      252,  252,  255,  255,  251,  251,  252,  252,  255,  255,
      265,  256,  256,  257,  257,  263,  251,  256,  256,  259,
      259,  261,  261,  264,  264,  266,  266,  269,  269,  271,
      271,  273,  273,  274,  274,  277,  277,  273,  273,  274,
      274,  277,  277,  260,  278,  278,  279,  279,  253,  273,
      278,  278,  281,  281,  282,  282,  283,  283,  285,  285,
      282,  282,  287,  287,  289,  289,  292,  292,  282,  291,
      291,  294,  294,  296,  296,  291,  291,  298,  298,  302,
      302,  304,  304,  291,  300,  300,  308,  308,  310,  310,

      300,  300,  248,  320,  320,  246,  300,  306,  306,  320,
      320,  321,  321,  306,  306,  332,  332,  321,  321,  306,
      312,  312,  322,  322,  325,  325,  312,  312,  322,  322,
      325,  325,  334,  334,  335,  335,  326,  326,  243,  312,
      313,  313,  326,  326,  327,  327,  313,  313,  330,  330,
      327,  327,  337,  337,  330,  330,  331,  331,  241,  313,
      314,  314,  331,  331,  339,  339,  314,  314,  341,  341,
      344,  344,  238,  314,  315,  315,  346,  346,  234,  228,
      315,  315,  226,  217,  215,  212,  210,  315,  316,  316,
      207,  205,  201,  199,  316,  316,  195,  189,  187,  178,

      176,  173,  171,  168,  316,  317,  317,  166,  162,  160,
      150,  317,  317,  145,  119,  114,   90,   83,   78,   73,
       68,  317,  318,  318,   60,   53,   48,   43,  318,  318,
       40,   36,    9,    5,    3,    1,    0,  318,  319,  319,
        0,    0,    0,    0,  319,  319,    0,    0,    0,    0,
        0,    0,    0,  319,  349,  349,  350,  350,  352,  352,
      353,  353,  354,  354,  355,  355,  356,  356,  357,  357,
      358,  358,  359,  359,  360,  360,  361,  361,  362,  362,
      363,  363,  364,  364,  365,  365,  366,  366,  367,  367,
      368,  368,  369,  369,  370,  370,  371,  371,  372,  372,

      373,  373,  374,  374,  375,  375,  376,  376,  377,  377,
      378,  378,  379,  379,  380,  380,  381,  381,  382,  382,
      383,  383,  384,  384,  385,  385,  386,  386,  387,  387,
      388,  388,  389,  389,  390,  390,  391,  391,  392,  392,
      393,  393,  394,  394,  395,  395,  396,  396,  397,  397,
      398,  398,  399,  399,  400,  400,  401,  401,  402,  402,
      403,  403,  404,  404,  405,  405,  406,  406,  407,  407,
      408,  408,  409,  409,  410,  410,  411,  411,  412,  412,
      413,  413,  414,  414,  415,  415,  416,  416,  417,  417,
      418,  418,  419,  419,  420,  420,  421,  421,  422,  422,

      423,  423,  424,  424,  425,  425,  426,  426,  427,  427,
      428,  428,  429,  429,  430,  430,  431,  431,  432,  432,
      433,  433,  434,  434,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[20] =
    {   0,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "atf.l"
#line 5 "atf.l"
#include <oraccsys.h>
#include <mesg.h>
#include <pool.h>

#define ATFLTYPE Mloc
#include "atf.tab.h"
#define YY_USER_ACTION atf_user_action();
extern Mloc atflloc;
const char *atffile = "<stdin>";
const char *curratffile = NULL;

int atfflextrace = 0;

extern Pool *catpool;
#define atfpool(s) (char*)pool_copy((const unsigned char*)(s),catpool);
static void atf_user_action(void);

/* #if 1 to print every matched rule */
#if 0
#define pmatch(m) fprintf(stderr, (m))
#else
#define pmatch(m)
#endif

#define atfsave atflval.text=atfpool(atftext)

#line 1118 "<stdout>"

#line 1120 "<stdout>"

#define INITIAL 0
#define T 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 39 "atf.l"


#line 1342 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 349 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 348 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 41 "atf.l"
{ atflval.text=atfpool(atftext+3); pmatch("###amp\n"); return TOK; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 43 "atf.l"
{ atflval.text=atfpool(atftext+2); pmatch("###amp\n"); return TOK; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 45 "atf.l"
{ BEGIN 0; atfsave; pmatch("###amp\n"); return TOK; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 47 "atf.l"
{ BEGIN T; atfsave; pmatch("###translation\n"); return TOK; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 49 "atf.l"
{ atfsave; pmatch("###at\n"); return TOK; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 51 "atf.l"
{ atfsave; pmatch("###dollar\n"); return TOK; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 53 "atf.l"
{ atfsave; pmatch("###hash\n"); return TOK; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 55 "atf.l"
{ atfsave; pmatch("###link\n"); return TOK; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 57 "atf.l"
{ atfsave; pmatch("###line\n"); return TOK; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 59 "atf.l"
{ atfsave; pmatch("###siglum\n"); return TOK; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 61 "atf.l"
{ atfsave; pmatch("###equiv\n"); return TOK; }
	YY_BREAK
case 12:
/* rule 12 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 63 "atf.l"
{ atfsave; pmatch("###comment\n"); return CMT; }
	YY_BREAK
case 13:
/* rule 13 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 65 "atf.l"
{ atfsave; pmatch("###tab\n"); return TAB; }
	YY_BREAK
case 14:
/* rule 14 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 67 "atf.l"
{ atfsave; pmatch("###bad\n"); return TRANS; }
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 69 "atf.l"
{ pmatch("###bad\n"); return BAD; }
	YY_BREAK
case 16:
/* rule 16 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 71 "atf.l"
{ pmatch("###par\n"); return PAR; }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 73 "atf.l"
{ pmatch("###eol\n"); return EOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 75 "atf.l"
{ mesg_vwarning(curratffile, atflineno,
						"atf.l: unmatched character %c\n", *atftext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "atf.l"
ECHO;
	YY_BREAK
#line 1583 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(T):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 349 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 349 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 348);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 78 "atf.l"


void
atf_lex_init(FILE *fp, const char *file)
{
#if 1
  static ssize_t fsize;
  char *buf = (char*)slurp("atf", file, &fsize);
#else
  YY_FLUSH_BUFFER;
  yyrestart(fp);
#endif
  atffile = curratffile = file;
  atflineno = 1;
#if 1
  /* slurp adds \n\0\0 but only counts \n in the returned fsize */
  atf_scan_buffer(buf,fsize+2);
#endif
}

static void
atf_user_action(void)
{
  if (atfflextrace)
    fprintf(stderr, "%s:%d: atflex: text=::%s::\n", curratffile, atflineno, atftext);

  atflloc.file = curratffile;
  atflloc.line = yylineno;
}

