#define s_bp 1
#define s_ba 2
#define s_cf 3
#define s_f 4
#define s_flag 5
#define s_flush 6
#define s_gw 7
#define s_incl 8
#define s_pos 9
#define s_sol 10
#define s_s 11
#define s_text 12
#define s_word 13
#define s_allow 14
#define s_equiv 15
