#ifndef O2_H_
#define O2_H_
#define label_frag	o2_label_frag
#define atf_term	o2_atf_term
#define trans_abbrevved_labels	o2_trans_abbrevved_labels
#define tlit_parse_inline	o2_tlit_parse_inline
#define register_label	o2_register_label
#define reset_mlabel	o2_reset_mlabel
#define label_table	o2_label_table
#define mylines	o2_mylines
#define translations	o2_translations
#define trans_parenned_labels	o2_trans_parenned_labels
#define exemplar_offset	o2_exemplar_offset
#define bil_offset	o2_bil_offset
#define label_from_line_id	o2_label_from_line_id
#define label2	o2_label2
#define last_tlit_h_hash	o2_last_tlit_h_hash
#define max_trans_cols	o2_max_trans_cols
#define note_term	o2_note_term
#define note_index	o2_note_index
#define atffile	o2_atffile
#define define_labels_symbol	o2_define_labels_symbol
#define label_to_id	o2_label_to_id
#define line_id_insertp	o2_line_id_insertp
#define saa_mode	o2_saa_mode
#define label_term	o2_label_term
#define header_id	o2_header_id
#define line_id	o2_line_id
#define newlabel	o2_newlabel
#define find_label	o2_find_label
#define m_label_col_index	o2_m_label_col_index
#define note_initialize_text	o2_note_initialize_text
#define set_tr_id	o2_set_tr_id
#define load_labels	o2_load_labels
#define roman	o2_roman
#define line_label	o2_line_label
#define update_mlabel	o2_update_mlabel
#define label_segtab	o2_label_segtab
#define suppress_lem	o2_suppress_lem
#define div_level	o2_div_level
#define line_label_buf	o2_line_label_buf
#define m_label2	o2_m_label2
#define load_labels_term	o2_load_labels_term
#define check_label	o2_check_label
#define reset_labels	o2_reset_labels
#define start_lnum	o2_start_lnum
#define already_lemmed	o2_already_lemmed
#define note_initialize	o2_note_initialize
#define need_alignment	o2_need_alignment
#define note_initialize_line	o2_note_initialize_line
#define atf_init	o2_atf_init
#define note_number_by_run	o2_note_number_by_run
#define lnstrsp	o2_lnstrsp
#define nocellspan	o2_nocellspan
#define current_trans	o2_current_trans
#define tlit_reinit_inline	o2_tlit_reinit_inline
#define lninfo	o2_lninfo
#define load_labels_init	o2_load_labels_init
#define lnstrs	o2_lnstrs
#define reset_lninfo	o2_reset_lninfo
#endif/*O2_H_*/
